

version: "3.9"

volumes:
  app:

services:

  traefik:
    image: "traefik:v2.6"

    command:
      - "--api.insecure=false"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

    ports:
      - "80:80"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  app:
    build: .
    ports:
      - "8000"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.demo`)"
      - "traefik.http.routers.app.entrypoints=web"

    extra_hosts:
      - "host.docker.internal:host-gateway"


